### ISSUE TITLE
what is folds.csv?

### ISSUE THREAD

**Issue by u101022205** [selimsef/dsb2018_topcoders#1]
Hello, 

i was looking at your code. There is one file, folds.csv. What is this like? Can you upload one example here? Thank you. I saw there are four information inside the file.  'img_id',` 'fold', 'cluster', 'source'
i can understand the first one, but not the rest of them. If you can provide one example, it will be great. Thanks

**Comment by selimsef** [comment]
Hi,
the file looks like this

|     |                                                                  |             |            |                 |      |         |        |          | 
|-----|------------------------------------------------------------------|-------------|------------|-----------------|------|---------|--------|----------| 
| idx | img_id                                                           | HSV_CLUSTER | mosaic_idx | mosaic_position | fold | cluster | source | hold_out | 
| 0   | 55ff2b0ec48b76e10c7ee18add5794005cd551697f96af865c763d50da78dd9c | 1           | 76         |                 | 3    | f       | train  | 0        | 
| 1   | ae570a676961482848b5097038ef5e407df7a66a8e1c9b0567da599565a6b142 | 2           | 0          | down_left       | 0    | c       | train  | 1        | 
| 2   | 40bcdad218ac5f0885fc247d88fcad9f729f55c81c79d241a8f1559b6d8c0574 | 1           | 77         |                 | 0    | f       | train  | 0        | 
| 3   | 337b6eed0726f07531cd467cd62b6676c31a8c9e716bdbc49433986c022252cf | 2           | 1          | down_right      | 3    | b       | train  | 0        | 

`hold_out` was not used in the end as we had kfold split.
`mosaic_idx` if several images have the same id then they are actually tiles of one image and should not be in train/val at the same time to avoid data leak. 
`cluster` manual clustering of images of different types, was used for oversampling.

**Comment by u101022205** [comment]
Thank you. But what is fold? If you already mentioned and i didn't read it, i am sorry. But i don't really find any explanation. Thanks

**Comment by selimsef** [comment]
Column fold shows if the record is in holdout set for this fold. I.e. if fold=3 then the record is in val set for the third fold. 
The split was made partially manually but could be done with Stratified KFold or something like that.

**Comment by comfort4u** [comment]
What is it used for

**Comment by comfort4u** [comment]
![Screenshot_20200325-184515](https://user-images.githubusercontent.com/34754950/77593475-a2ae4300-6eca-11ea-97d5-562fc22a11ad.png)
