### ISSUE TITLE
Empty nn_models

### ISSUE THREAD

**Issue by paulxiong** [selimsef/dsb2018_topcoders#12]
selim# ./predict_test.sh, got error with build model:.... "Building model resnet101_2 from weights nn_models/best_resnet101_2_fold0.h5"

Check on nn_models, there is nothing... 

My question: would you point where can I find the download link?

**Comment by selimsef** [comment]
Models are around 10GB overall. I'm considering adding models as a release

**Comment by dkermany** [comment]
That would be greatly appreciated!

**Comment by selimsef** [comment]
Added link to models, see readme.
