### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Conv2D'

### ISSUE THREAD

**Issue by anusha-devulapally** [selimsef/dsb2018_topcoders#18]
while i am trying to execute predict_test.sh in victor folder
I am getting issue :
in predict_inception.py
---> model = get_inception_resnet_v2_unet_softmax((None,None), weights=None)

in models.py
def get_inception_resnet_v2_unet_softmax(input_shape, weights='imagenet'):
    inp = Input(input_shape + (4,))
    print("inp",inp)
    # Stem block: 35 x 35 x 192
--->    x = conv2d_bn(inp, 32, 3, strides=2, padding='same')
    x = conv2d_bn(x, 32, 3, padding='same')

**Comment by selimsef** [comment]
The version of Keras/Pytorch are quite old. Unfortunately, I doubt it will work out of the box with current versions of libraries.
