### ISSUE TITLE
unable to reproduce the masks

### ISSUE THREAD

**Issue by inumella-sricharan** [selimsef/dsb2018_topcoders#19]
Hi, I'm trying to generate the masks for training data using your code below. Just to be sure that I am doing everything correctly I compared the mask generated from this code and the mask present in the already existing dataset that you provided via the dropbox link. They aren't quire right. The separation between nuclei is not fully done. My major suspicion is if the changes in the versions of the libraries used has affected this or I'm making a silly mistake somewhere. Could you please let me know where I'm going wrong ?

`

    def create_mask(img_id):
        labels = cv2.imread(path.join(labels_folder, '{0}.tif'.format(img_id)), cv2.IMREAD_UNCHANGED)
        tmp = dilation(labels > 0, square(9))    
        tmp2 = watershed(tmp, labels, mask=tmp, watershed_line=True) > 0
        tmp = tmp ^ tmp2
        tmp = dilation(tmp, square(7))
        msk = (255 * tmp).astype('uint8')
    
        props = measure.regionprops(labels)
        msk0 = 255 * (labels > 0)
        msk0 = msk0.astype('uint8')
    
        msk1 = np.zeros_like(labels, dtype='bool')
    
        max_area = np.max([p.area for p in props])
    
        for y0 in range(labels.shape[0]):
            for x0 in range(labels.shape[1]):
                if not tmp[y0, x0]:
                    continue
                if labels[y0, x0] == 0:
                    if max_area > 4000:
                        sz = 6
                    else:
                        sz = 3
                else:
                    sz = 3
                    if props[labels[y0, x0] - 1].area < 300:
                        sz = 1
                    elif props[labels[y0, x0] - 1].area < 2000:
                        sz = 2
                uniq = np.unique(labels[max(0, y0-sz):min(labels.shape[0], y0+sz+1), max(0, x0-sz):min(labels.shape[1], x0+sz+1)])
                if len(uniq[uniq > 0]) > 1:
                    msk1[y0, x0] = True
                    msk0[y0, x0] = 0
    
        msk1 = 255 * msk1
        msk1 = msk1.astype('uint8')
    
        msk2 = np.zeros_like(labels, dtype='uint8')
        msk = np.stack((msk0, msk1, msk2))
        msk = np.rollaxis(msk, 0, 3)
    
        cv2.imwrite(path.join(masks_out_folder, '{0}.png'.format(img_id)), msk, [cv2.IMWRITE_PNG_COMPRESSION, 9])
        return 0
`

id : 00ae65c1c6631ae6f2be1a449902976e6eb8483bf6b0740d00530220832c6d3e
platform : google colab

After running the code:
![image](https://user-images.githubusercontent.com/66732085/130604409-2db6d066-25e0-4aa8-a04a-99987f3a7dc5.png)
Directly from the dataset :
![image](https://user-images.githubusercontent.com/66732085/130604538-45c5442b-643e-4c87-b725-571f6e759c75.png)

**Comment by deepak2837** [comment]
please attach the code that u have used

**Comment by selimsef** [comment]
This approach was used in multiple competitions aftewards and became quite common for building footprints segmentation. You can have a look at different implementations in https://github.com/SpaceNetChallenge
