### ISSUE TITLE
where are the tif format labels?

### ISSUE THREAD

**Issue by LXYTSOS** [selimsef/dsb2018_topcoders#4]
I'm quite confused about your code `lbl = cv2.imread(os.path.join(labels_dir, '{0}.tif'.format(img_id)), cv2.IMREAD_UNCHANGED)` in dsb_binary.py, because I can't find any tif format labels in the data that Kaggle provided, could you please tell me how did you preprocess the data?

**Comment by selimsef** [comment]
Labels were generated from original masks. They just represent labeled ground truth masks as a single image, i.e. single channel, different object have different pixel values. PNG could be used as well provided that there are no more than 255 objects on a single image.

**Comment by LXYTSOS** [comment]
And could you make a list of how many arguments should I pass to `train.py` and its meaning? It seems a lot of arguments that used for training are not passed to `train.py` according to `train_all.sh` such as alias, schedule, etc.

**Comment by selimsef** [comment]
Default parameters are specified in the file params.py

**Comment by LXYTSOS** [comment]
Thank you very much.

**Comment by LXYTSOS** [comment]
I don't quite understand these codes in dsb_binary.py:
`img_id = all_ids[i]
msk = cv2.imread(os.path.join(masks_dir, '{0}.png'.format(img_id)), cv2.IMREAD_UNCHANGED)
lbl = cv2.imread(os.path.join(labels_dir, '{0}.tif'.format(img_id)), cv2.IMREAD_UNCHANGED)
 tmp = np.zeros_like(msk[..., 0], dtype='uint8')
 tmp[1:-1, 1:-1] = msk[1:-1, 1:-1, 0]
good4copy = list(set(np.unique(lbl[lbl > 0])).symmetric_difference(np.unique(lbl[(lbl > 0) & (tmp == 0)])))`
what are the img_id.png and img_id.tif here? and why were you do the symmetric_difference?

**Comment by selimsef** [comment]
This code is related to nuclei copy augmentation

**Comment by LXYTSOS** [comment]
Could you be more specific about how to do the nuclei augmentation and create those img_id.png masks and img_id.tif labels?
