### ISSUE TITLE
how to set "dirs"?

### ISSUE THREAD

**Issue by Bonsen** [selimsef/dsb2018_topcoders#7]
like "train_dir", "mask_dir" and  "label_dir" in train.py (selim)
it seems only stage1_train and stage1_test.

**Comment by selimsef** [comment]
default parameters are specified in `params.py`

**Comment by Bonsen** [comment]
hi, @selimsef 
What's the "labels_dir"?
Thanks

**Comment by selimsef** [comment]
It was explained in #4

**Comment by dpei** [comment]
hi @Bonsen , If you want to set up "train_dir", "mask_dir" and "label_dir" in your directory, you might have to:

1. Move /train_stage1 (downloaded from Kaggle) directory to ~/dsb2018_topcoders/data/
2. Change line 15 in create_stage1_labels.py to data_folder = path.join(root_data_folder, 'stage1_train').
3. run this code by type 'python  create_stage1_labels.py'
4. run 'python  create_masks.py'

Now you should have 670 files in each of the three folders "train_dir", "mask_dir" and "label_dir"
If that does not work, let me know.

**Comment by yfq512** [comment]
Hi! @selimsef @dpei what is in folder:"labels_all"? ***.csv?or others?
I run 'python create_masks.py', but nothing product.
Can you show the directory about train data?

**Comment by selimsef** [comment]
You can download all the data. Updated readme with dropbox link.

**Comment by yfq512** [comment]
@selimsef   Thanks for your trian data and models! Your answer helped me a lot 
 Now I have some questions about predict.  When  run './predict_test.sh', It will enter an infinite loop, maybe my predict directory is wrong. Can you show the original predict directory and run which scripts in detail? Waiting for your reply!
