### ISSUE TITLE
How do the three input folders correspond to each other?

### ISSUE THREAD

**Issue by li-pengcheng** [selimsef/dsb2018_topcoders#8]
In this code, i found there have three input folders: images_all, masks_all and labels_all,
could U please help me in detail how to set the original images and masks to these folders?
because i found that a image correspond many masks.

**Comment by selimsef** [comment]
- images_all - images in flat structure
- masks_all - generated masks (3 channels masks) with borders. See create_masks file for details
- labels_all object labels, i.e. single channel masks where each object has different int value for its pixels

**Comment by dpei** [comment]
#7 may answers your question. Let me know if it does. @lpengc
