### ISSUE TITLE
ImportError: cannot import name 'inception_resnet_block'

### ISSUE THREAD

**Issue by jyning12** [selimsef/dsb2018_topcoders#9]
hi, thank you very much for you codes,  when I predict on the test data, get a  ImportError:
from keras.applications.inception_resnet_v2 import InceptionResNetV2, inception_resnet_block, conv2d_bn
ImportError: cannot import name 'inception_resnet_block'

**Comment by RunHoujianjiang** [comment]
keras.applications.inception_resnet_v2  to keras_applications.inception_resnet_v2.
